name: Make It Rane
favicon: null
layout_spectrum: 0.8285479426849633
typography_spectrum: 0.946590120671317
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.06869900622405112
  lightness: 0.5289165028370917
  saturation: 0.8903552738483995
  rhythmicContrast: 0.5192629531957209
purpose: []
